title = "SeafoodQuotes.co"
baseURL = "www.example.com"
languageCode = "en-us"
themesDir = "../.."
theme = "hugo-serif-theme"

[params]
google_analytics_id = ""
google_tag_manager_id = ""

[params.homepage_meta_tags]
meta_description = "SeafoodQuotes.co is the fastest, most efficient way to obtain pricing quotes from multiple distributors."
meta_og_description = "SeafoodQuotes.co is the fastest, most efficient way to obtain pricing quotes from multiple distributors."
meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
meta_og_title = "SeafoodQuotes.co"
meta_og_type = "website"
meta_og_url = "https://seafoodquotes.co"
meta_twitter_card = "summary"
meta_twitter_creator = "@seafoodquotesco"
meta_twitter_site = "@seafoodquotesco"

[params.logo]
alt = "Serif - A Hugo Business Theme"
mobile = "images/logo-mobile.svg"
standard = "images/logo.svg"

[menu]

[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2

[[menu.main]]
name = "Services"
url = "/services/"
weight = 1

[[menu.main]]
name = "Team"
url = "/team/"
weight = 2